//common types
export const TOGGLE_ON_CLICK = 'TOGGLE_ON_CLICK';
export const USER_SCROLLED = 'USER_SCROLLED';
//loader types
export const BRING_ON_LOADER = 'BRING_ON_LOADER';
export const FUCK_THE_LOADER = 'FUCK_THE_LOADER';

export const FETCHING_CLUB_POSTS = 'FETCHING_CLUB_POSTS';
export const FETCHED_CLUB_POSTS = 'FETCHED_CLUB_POSTS';

export const FETCHED_BASIC_INFO = 'FETCHED_BASIC_INFO';
export const FETCHNG_BASIC_INFO = 'FETCHNG_BASIC_INFO';

export const FETCHING_STU_POSTS = 'FETCHING_STU_POSTS';
export const FETCHED_STU_POSTS = 'FETCHED_STU_POSTS';

export const FETCHED_CONFS_POSTS = 'FETCHED_CONFS_POSTS';
export const FETCHING_CONFS_POSTS = 'FETCHING_CONFS_POSTS';

//register page types
export const UPDATE_ONCHANGE_REGISTER_FORM = 'UPDATE_ONCHANGE_REGISTER_FORM';
export const TEXT_TO_SHOW_ON_DONE = 'TEXT_TO_SHOW_ON_DONE';

export const UPDATE_POST_REDUCER = 'UPDATE_POST_REDUCER';

export const UPDATE_CONF_REDUCER = 'UPDATE_CONF_REDUCER';

export const SEARCH_RESULT_IF_FETCHING = 'SEARCH_RESULT_IF_FETCHING';


export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
export const ON_CHANGE_LOGIN_FORM = 'ON_CHANGE_LOGIN_FORM';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const UPDATE_ONCHANGE_LOGIN_FORM = 'UPDATE_ONCHANGE_LOGIN_FORM';

export const UPDATA_BASIC_INFORMATION = 'UPDATA_BASIC_INFORMATION';

export const UPDATA_SEARCH_BODY = 'UPDATA_SEARCH_BODY';

export const UPDATA_PROFILE_INFORMATION = 'UPDATA_PROFILE_INFORMATION';

export const ADD_FILE_TO_ADD_POST = 'ADD_FILE_TO_ADD_POST';

export const ADD_TEXT_TO_ADD_POST = 'ADD_TEXT_TO_ADD_POST';

export const LOADING_LOGIN_FORM = 'LOADING_LOGIN_FORM';

export const UPLOAD_NEW_POST = 'UPLOAD_NEW_POST';

export const REMOVE_PHOTO_FROM_ADD_POST = 'REMOVE_PHOTO_FROM_ADD_POST';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const UPDATE_STU_POST_REDUCER = 'UPDATE_STU_POST_REDUCER';

export const SUCCESFULLY_LIKED_POST = 'SUCCESFULLY_LIKED_POST';

export const SUCCESFULLY_LIKED_STU_POST = 'SUCCESFULLY_LIKED_STU_POST';

export const SUCCESFULLY_UNLIKED_STU_POST = 'SUCCESFULLY_UNLIKED_STU_POST';

export const SUCCESFULLY_UNLIKED_POST = 'SUCCESFULLY_UNLIKED_POST';

export const FIRST_UPDATA_EDIT_PROFILE = 'FIRST_UPDATA_EDIT_PROFILE';

export const PREVIEW_NEW_EDIT_PROFILE = 'PREVIEW_NEW_EDIT_PROFILE';

export const PREVIEW_NEW_EDIT_PROFILE_PIC = 'PREVIEW_NEW_EDIT_PROFILE_PIC';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const UPDATA_PROFILE_POSTS = 'UPDATA_PROFILE_POSTS';

export const SUCCESFULLY_AUTH_CONF = 'SUCCESFULLY_AUTH_CONF';

export const ADD_TEXT_TO_ADD_CONF = 'ADD_TEXT_TO_ADD_CONF';

export const CHANGE_THEME_OF_ADD_CONF = 'CHANGE_THEME_OF_ADD_CONF';

export const ADD_PROBLEM_IN_ADD_POST = 'ADD_PROBLEM_IN_ADD_POST';

export const CHANGE_IN_ADD_CLUB_FORM = 'CHANGE_IN_ADD_CLUB_FORM';

export const REMOVE_USER_ON_LOGOUT = 'REMOVE_USER_ON_LOGOUT';

export const CHANDE_TYPE_OF_REGISTRATION_FORM = 'CHANDE_TYPE_OF_REGISTRATION_FORM';

export const DELETE_POST_FROM_STUDENTS_POST = 'DELETE_POST_FROM_STUDENTS_POST';

export const DELETE_POST_FROM_PROFILE_POST = 'DELETE_POST_FROM_PROFILE_POST';

export const DELETE_POST_FROM_CLUB_POST = 'DELETE_POST_FROM_CLUB_POST';
